'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class GestionTVA

    '''<summary>
    '''tbNouveauTaux control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbNouveauTaux As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvDateDeb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvDateDeb As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''revTbNouveauTaux control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents revTbNouveauTaux As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''btnAjouterNouveau control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAjouterNouveau As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''gvTva control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvTva As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''btnEnregistrer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEnregistrer As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblEnregistrement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEnregistrement As Global.System.Web.UI.WebControls.Label
End Class
