'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class GestionService

    '''<summary>
    '''tbNouveauLibelle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbNouveauLibelle As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvDateDeb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvDateDeb As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''cbNouveauServiceActif control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbNouveauServiceActif As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''tbNouveauServiceObjectif control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbNouveauServiceObjectif As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''revTbNouveauServiceObjectif control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents revTbNouveauServiceObjectif As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''tbNouveauServiceDureeMouvement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbNouveauServiceDureeMouvement As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''revTbNouveauServiceDureeMouvement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents revTbNouveauServiceDureeMouvement As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''btnAjouterNouveau control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAjouterNouveau As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''gvService control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvService As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''btnEnregistrer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEnregistrer As Global.System.Web.UI.WebControls.Button
End Class
