'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class RIB

    '''<summary>
    '''hTitreListeCoordonnéesBancaires control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hTitreListeCoordonnéesBancaires As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblRibID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRibID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnNouveau control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNouveau As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''fsNouveau control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fsNouveau As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''legend control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents legend As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblLibelleRib control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLibelleRib As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbLibelleRib control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbLibelleRib As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblCP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCP As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbCP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbCP As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblCC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCC As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbCC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbCC As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblCB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCB As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbCB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbCB As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblCG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCG As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbCG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbCG As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblNC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNC As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbNC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbNC As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblCle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbCle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbCle As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblBic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBic As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbBic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbBic As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblDefault control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDefault As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbDefault control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbDefault As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''btnEnregistrer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEnregistrer As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''rfvLibelleRib control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvLibelleRib As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''RangeValidatorCC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RangeValidatorCC As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''CompareValidatorCB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CompareValidatorCB As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''rfvCB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvCB As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''CompareValidatorCG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CompareValidatorCG As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''rfvCG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvCG As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''rfvNC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvNC As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''rf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rf As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''CompareValidatorCle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CompareValidatorCle As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''lblMsgError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsgError As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsg As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gvCoordonnéesBancaires control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvCoordonnéesBancaires As Global.System.Web.UI.WebControls.GridView
End Class
