'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class StatCoutsSalariaux

    '''<summary>
    '''cbbPeriodeAnnee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbbPeriodeAnnee As Global.Obout.ComboBox.ComboBox

    '''<summary>
    '''cbbPeriodeMois control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbbPeriodeMois As Global.Obout.ComboBox.ComboBox

    '''<summary>
    '''ComboBoxItem0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ComboBoxItem0 As Global.Obout.ComboBox.ComboBoxItem

    '''<summary>
    '''ComboBoxItem1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ComboBoxItem1 As Global.Obout.ComboBox.ComboBoxItem

    '''<summary>
    '''ComboBoxItem2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ComboBoxItem2 As Global.Obout.ComboBox.ComboBoxItem

    '''<summary>
    '''ComboBoxItem3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ComboBoxItem3 As Global.Obout.ComboBox.ComboBoxItem

    '''<summary>
    '''ComboBoxItem5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ComboBoxItem5 As Global.Obout.ComboBox.ComboBoxItem

    '''<summary>
    '''ComboBoxItem6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ComboBoxItem6 As Global.Obout.ComboBox.ComboBoxItem

    '''<summary>
    '''ComboBoxItem7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ComboBoxItem7 As Global.Obout.ComboBox.ComboBoxItem

    '''<summary>
    '''ComboBoxItem9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ComboBoxItem9 As Global.Obout.ComboBox.ComboBoxItem

    '''<summary>
    '''ComboBoxItem8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ComboBoxItem8 As Global.Obout.ComboBox.ComboBoxItem

    '''<summary>
    '''ComboBoxItem4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ComboBoxItem4 As Global.Obout.ComboBox.ComboBoxItem

    '''<summary>
    '''ComboBoxItem10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ComboBoxItem10 As Global.Obout.ComboBox.ComboBoxItem

    '''<summary>
    '''ComboBoxItem11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ComboBoxItem11 As Global.Obout.ComboBox.ComboBoxItem

    '''<summary>
    '''cbbEmployeActif control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbbEmployeActif As Global.Obout.ComboBox.ComboBox

    '''<summary>
    '''cbbTousActifs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbbTousActifs As Global.Obout.ComboBox.ComboBoxItem

    '''<summary>
    '''cbbTous control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbbTous As Global.Obout.ComboBox.ComboBoxItem

    '''<summary>
    '''btnRechercheStat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRechercheStat As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''gvStatCoutSalaire control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvStatCoutSalaire As Global.System.Web.UI.WebControls.GridView
End Class
