'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class StatitiquesGenerales

    '''<summary>
    '''LabelTri control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelTri As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbDateDeb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbDateDeb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cDateDeb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cDateDeb As Global.OboutInc.Calendar2.Calendar

    '''<summary>
    '''tbDateFin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbDateFin As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cDateFin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cDateFin As Global.OboutInc.Calendar2.Calendar

    '''<summary>
    '''cbn1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbn1 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbn2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbn2 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblRestriction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRestriction As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbbFiltreStatGeneral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbbFiltreStatGeneral As Global.Obout.ComboBox.ComboBox

    '''<summary>
    '''cbbItemToutEmploye control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbbItemToutEmploye As Global.Obout.ComboBox.ComboBoxItem

    '''<summary>
    '''cbbItemToutService control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbbItemToutService As Global.Obout.ComboBox.ComboBoxItem

    '''<summary>
    '''cbbFiltreStatGalDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbbFiltreStatGalDetail As Global.Obout.ComboBox.ComboBox

    '''<summary>
    '''btnRechercheStat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRechercheStat As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''btnExporter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnExporter As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLegendeRAIncomplet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLegendeRAIncomplet As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRAnonComplet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRAnonComplet As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLegendeDepassement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLegendeDepassement As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDep control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDep As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rfvTbDateDeb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvTbDateDeb As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''rfvDateFin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvDateFin As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''rfvCbbFiltre1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvCbbFiltre1 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''gvStatGenerales control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvStatGenerales As Global.System.Web.UI.WebControls.GridView
End Class
