'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class GestionTypeProduit

    '''<summary>
    '''tbNouveauLibelle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbNouveauLibelle As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvLibelle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvLibelle As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''cbNouveauTypeProduitVisible control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbNouveauTypeProduitVisible As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbNouveauTypeProduitAffaire control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbNouveauTypeProduitAffaire As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbNouveauTypeProduitBudgetAffaire control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbNouveauTypeProduitBudgetAffaire As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbNouveauTypeProduitJournee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbNouveauTypeProduitJournee As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbNouveauTypeProduitCA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbNouveauTypeProduitCA As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbNouveauTypeProduitCAAxe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbNouveauTypeProduitCAAxe As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbNouveauTypeProduitFactQualif control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbNouveauTypeProduitFactQualif As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbNouveauTypeProduitFactInterne control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbNouveauTypeProduitFactInterne As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''btnAjouterNouveau control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAjouterNouveau As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblMsgSupp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsgSupp As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gvTypeProduit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvTypeProduit As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''btnEnregistrer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEnregistrer As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblEnregistrement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEnregistrement As Global.System.Web.UI.WebControls.Label
End Class
