'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AffaireLister

    '''<summary>
    '''ScriptManagerTEST control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManagerTEST As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''btnInsererAffaire control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnInsererAffaire As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblNoAffaire control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoAffaire As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tvAffaires control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tvAffaires As Global.Obout.Ajax.UI.TreeView.Tree

    '''<summary>
    '''LabelTri control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelTri As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbbChampRechercheAffaire control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbbChampRechercheAffaire As Global.Obout.ComboBox.ComboBox

    '''<summary>
    '''cbbItemClient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbbItemClient As Global.Obout.ComboBox.ComboBoxItem

    '''<summary>
    '''cbbItemType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbbItemType As Global.Obout.ComboBox.ComboBoxItem

    '''<summary>
    '''cbbItemBU control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbbItemBU As Global.Obout.ComboBox.ComboBoxItem

    '''<summary>
    '''Labelcharge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Labelcharge As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbbEmploye control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbbEmploye As Global.Obout.ComboBox.ComboBox

    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDateDebut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDateDebut As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbDateDeb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbDateDeb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cDateDeb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cDateDeb As Global.OboutInc.Calendar2.Calendar

    '''<summary>
    '''lblDateFin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDateFin As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbDateFin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbDateFin As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cDateFin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cDateFin As Global.OboutInc.Calendar2.Calendar

    '''<summary>
    '''Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rbAffaireFiltre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbAffaireFiltre As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblCompteurAffaire control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCompteurAffaire As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ibValider control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibValider As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ibExporter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibExporter As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''btnReinit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnReinit As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblPeriodeIncorrete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPeriodeIncorrete As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CompareValidator1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CompareValidator1 As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''mMenuBouton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mMenuBouton As Global.System.Web.UI.WebControls.Menu

    '''<summary>
    '''lblMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsg As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''fs1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fs1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''tbClient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbClient As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbLibelle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbLibelle As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cbTerminee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbTerminee As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblAffaireID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAffaireID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbTypeAffaire control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbTypeAffaire As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbService control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbService As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbChargeDAffaire control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbChargeDAffaire As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbCom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbCom As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ibModifier control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibModifier As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ibDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibDelete As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''fs2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fs2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''tbBudget control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbBudget As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbHTconso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbHTconso As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbPrestRest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbPrestRest As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbFraisConso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbFraisConso As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbNbJoursPasses control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbNbJoursPasses As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbCtMoyen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbCtMoyen As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''fs3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fs3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''gvQualifAffaire control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvQualifAffaire As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''divTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divTotal As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbTotal As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''fs4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fs4 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''gvEtapesFactuPourcentage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvEtapesFactuPourcentage As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''tblMois control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblMois As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''tbhcMois1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbhcMois1 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''tbhcValidation1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbhcValidation1 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''affaireEtapeFactuID1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents affaireEtapeFactuID1 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''tbhcMois2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbhcMois2 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''tbhcValidation2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbhcValidation2 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''affaireEtapeFactuID2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents affaireEtapeFactuID2 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''cbMois1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbMois1 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblMois1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMois1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbMois7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbMois7 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblMois7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMois7 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbMois2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbMois2 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblMois2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMois2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbMois8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbMois8 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblMois8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMois8 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbMois3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbMois3 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblMois3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMois3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbMois9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbMois9 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblMois9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMois9 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbMois4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbMois4 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblMois4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMois4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbMois10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbMois10 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblMois10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMois10 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbMois5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbMois5 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblMois5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMois5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbMois11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbMois11 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblMois11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMois11 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbMois6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbMois6 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblMois6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMois6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbMois12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbMois12 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblMois12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMois12 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pPopupAlerteSuppression control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pPopupAlerteSuppression As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''btnAnnuler control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAnnuler As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnContinuer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnContinuer As Global.System.Web.UI.WebControls.Button
End Class
