'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AffaireModifier

    '''<summary>
    '''mMenuAffaireModif control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mMenuAffaireModif As Global.System.Web.UI.WebControls.Menu

    '''<summary>
    '''lblNonModif control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNonModif As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FSInfoGen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FSInfoGen As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblErreurInsertion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErreurInsertion As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbClient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbClient As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbLibelle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbLibelle As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cbTerminee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbTerminee As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblAffaireID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAffaireID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cCalendrier control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cCalendrier As Global.OboutInc.Calendar2.Calendar

    '''<summary>
    '''cbTypeAffaire control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbTypeAffaire As Global.Obout.ComboBox.ComboBox

    '''<summary>
    '''cbService control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbService As Global.Obout.ComboBox.ComboBox

    '''<summary>
    '''cbChargeAffaire control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbChargeAffaire As Global.Obout.ComboBox.ComboBox

    '''<summary>
    '''tbCom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbCom As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cvDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvDate As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''FSInfoBudget control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FSInfoBudget As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''revtbBudget control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents revtbBudget As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''tbBudget control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbBudget As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbHTconso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbHTconso As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbPrestRest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbPrestRest As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbFraisConso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbFraisConso As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbNbJoursPasses control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbNbJoursPasses As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbCtMoyen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbCtMoyen As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnValider control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnValider As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''FSQualif control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FSQualif As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblMsgQualif control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsgQualif As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gvQualifAffaire control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvQualifAffaire As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''divTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divTotal As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbTotal As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tableAjoutQualif control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tableAjoutQualif As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''listeQualif control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents listeQualif As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''tbPrixHT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbPrixHT As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbNbJours control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbNbJours As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnAjouter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAjouter As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''RegularExpressionValidator1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RegularExpressionValidator1 As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''RegularExpressionValidator2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RegularExpressionValidator2 As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''lblerror control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblerror As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FSFactu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FSFactu As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''gvEtapesFactuPourcentage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvEtapesFactuPourcentage As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''tblMois control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblMois As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''tbhcMois1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbhcMois1 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''tbhcValidation1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbhcValidation1 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''affaireEtapeFactuID1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents affaireEtapeFactuID1 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''tbhcMois2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbhcMois2 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''tbhcValidation2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbhcValidation2 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''affaireEtapeFactuID2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents affaireEtapeFactuID2 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''cbMois1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbMois1 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblMois1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMois1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbMois7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbMois7 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblMois7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMois7 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbMois2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbMois2 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblMois2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMois2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbMois8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbMois8 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblMois8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMois8 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbMois3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbMois3 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblMois3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMois3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbMois9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbMois9 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblMois9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMois9 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbMois4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbMois4 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblMois4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMois4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbMois10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbMois10 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblMois10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMois10 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbMois5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbMois5 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblMois5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMois5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbMois11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbMois11 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblMois11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMois11 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbMois6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbMois6 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblMois6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMois6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbMois12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbMois12 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblMois12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMois12 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ErreurPourcentage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ErreurPourcentage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnEnregistrerEtape control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEnregistrerEtape As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnRetourListe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRetourListe As Global.System.Web.UI.WebControls.Button
End Class
