'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class EmployeModifier

    '''<summary>
    '''lbInsererModifierUtilisateur control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbInsererModifierUtilisateur As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''mOnglets control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mOnglets As Global.System.Web.UI.WebControls.Menu

    '''<summary>
    '''modifEmpoye control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents modifEmpoye As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lEnregistrementOk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lEnregistrementOk As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbActif control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbActif As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''tbNom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbNom As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvTbNom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvTbNom As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''tbPrenom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbPrenom As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''revTbPrenom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents revTbPrenom As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''tbLogin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbLogin As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvTbLogin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvTbLogin As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''tbMotDePasse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbMotDePasse As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvTbMotDePasse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvTbMotDePasse As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''tbDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cCalendrier control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cCalendrier As Global.OboutInc.Calendar2.Calendar

    '''<summary>
    '''rvDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rvDate As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''rfvCcalendrier control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvCcalendrier As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''tbCoutFacturationInterne control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbCoutFacturationInterne As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvCoutFacturationInternet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvCoutFacturationInternet As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''rfvCoutFacturationInterne control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvCoutFacturationInterne As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''revtbCoutFacturationInterne control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents revtbCoutFacturationInterne As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''tbEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbEmail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''revtbEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents revtbEmail As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''lbService control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbService As Global.Obout.ComboBox.ComboBox

    '''<summary>
    '''lbProfil control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbProfil As Global.Obout.ComboBox.ComboBox

    '''<summary>
    '''lbQualification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbQualification As Global.Obout.ComboBox.ComboBox

    '''<summary>
    '''rbStatut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbStatut As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''rbSexe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbSexe As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''btValider control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btValider As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btRetourListeEmploye control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btRetourListeEmploye As Global.System.Web.UI.WebControls.Button
End Class
