'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AffaireFactureDetailsV2

    '''<summary>
    '''lblClientNom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblClientNom As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblClientAdresse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblClientAdresse As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblClientCPetVille control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblClientCPetVille As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFactureRefetDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFactureRefetDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCom As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbCommentaireFacture control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbCommentaireFacture As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblAxeTVA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAxeTVA As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblClientTVA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblClientTVA As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNumBC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNumBC As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbBC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbBC As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblCom2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCom2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbCommentaire2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbCommentaire2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''gvBonCommande control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvBonCommande As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lblSSTotalPresta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSSTotalPresta As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbSSTotalHT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbSSTotalHT As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblTVA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTVA As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbTVA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbTVA As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblTotalPresta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalPresta As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbSSTotalTTC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbSSTotalTTC As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''gvFrais control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvFrais As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''panelSSTotalFrais control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panelSSTotalFrais As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''legendeTableauFrais control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents legendeTableauFrais As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSSTotalFrais control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSSTotalFrais As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbSSTotalFrais control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbSSTotalFrais As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblTVAF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTVAF As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbTVAF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbTVAF As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblTotalFrais control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalFrais As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbTotalFrais control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbTotalFrais As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblToutTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblToutTotal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCondition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCondition As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRib control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRib As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRibAxe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRibAxe As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblIban control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIban As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblIbanNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIbanNum As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnRetour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRetour As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnEnregistrer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEnregistrer As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnExporter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnExporter As Global.System.Web.UI.WebControls.Button
End Class
