'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AffaireFactureDetails

    '''<summary>
    '''lblClientNom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblClientNom As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblClientAdresse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblClientAdresse As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblClientCPetVille control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblClientCPetVille As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFactureRefetDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFactureRefetDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAxeTVA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAxeTVA As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblClientTVA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblClientTVA As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gvProduitFacture control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvProduitFacture As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lblToutTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblToutTotal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnRetour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRetour As Global.System.Web.UI.WebControls.Button
End Class
