'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AffaireSousAffaireListe

    '''<summary>
    '''mMenuAffaireModif control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mMenuAffaireModif As Global.System.Web.UI.WebControls.Menu

    '''<summary>
    '''btnNouveau control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNouveau As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblSousAffaire control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSousAffaire As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gvListeSousAffaire control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvListeSousAffaire As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''btnRetourFiche control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRetourFiche As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnRetourListe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRetourListe As Global.System.Web.UI.WebControls.Button
End Class
