'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AffaireFacturation

    '''<summary>
    '''mMenuAffaireModif control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mMenuAffaireModif As Global.System.Web.UI.WebControls.Menu

    '''<summary>
    '''hTitrePageFacture control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hTitrePageFacture As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnNouveau control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNouveau As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnAvoir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAvoir As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsg As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''fsNouvelleFacture control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fsNouvelleFacture As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblNewRef control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNewRef As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFactureRef control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFactureRef As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNewLibelle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNewLibelle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbLibelle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbLibelle As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvLibelle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvLibelle As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblPourcentageMois control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPourcentageMois As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlPourcentageMoisFacturation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPourcentageMoisFacturation As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblDateFacture control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDateFacture As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbFactureDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbFactureDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Calendar1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Calendar1 As Global.OboutInc.Calendar2.Calendar

    '''<summary>
    '''lblRib control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRib As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlRib control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlRib As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblNumBonCommande control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNumBonCommande As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbNumBonCommande control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbNumBonCommande As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblErreurDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErreurDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnEnregistrer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEnregistrer As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnAnnuler control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAnnuler As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''fsAvoir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fsAvoir As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblReferenceAvoir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReferenceAvoir As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRefAv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRefAv As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLibelleAvoir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLibelleAvoir As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbLibelleAvoir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbLibelleAvoir As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvLibelleAvoir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvLibelleAvoir As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblMontantAvoir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMontantAvoir As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbMntAvoir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbMntAvoir As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvMntAvoir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvMntAvoir As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblDateAvoir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDateAvoir As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbDateAvoir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbDateAvoir As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Calendar2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Calendar2 As Global.OboutInc.Calendar2.Calendar

    '''<summary>
    '''lblRibAvoir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRibAvoir As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlRibAvoir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlRibAvoir As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnSaveAvoir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveAvoir As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnAnnulerAvoir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAnnulerAvoir As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''gvListeDesFactures control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvListeDesFactures As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''btnRetourFiche control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRetourFiche As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnRetourListe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRetourListe As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''pPopupSaveFacture control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pPopupSaveFacture As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''divSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divSave As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''FUSaveFacture control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUSaveFacture As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''lblErreurFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErreurFile As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tableBtn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tableBtn As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''btnArchiverPopUp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnArchiverPopUp As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnQuitter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnQuitter As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblRefArchivage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRefArchivage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFactureID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFactureID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pPopupSavePlusieursMois control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pPopupSavePlusieursMois As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''div1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''table2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents table2 As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''btnContinuer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnContinuer As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnQuitterSaveMois control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnQuitterSaveMois As Global.System.Web.UI.WebControls.Button
End Class
