'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AffaireFacturesListe

    '''<summary>
    '''lblCritere control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCritere As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblParCient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblParCient As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbbFiltreClient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbbFiltreClient As Global.Obout.ComboBox.ComboBox

    '''<summary>
    '''lblParBU control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblParBU As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbbFiltreService control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbbFiltreService As Global.Obout.ComboBox.ComboBox

    '''<summary>
    '''lblParTypeAffaire control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblParTypeAffaire As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbbFiltreType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbbFiltreType As Global.Obout.ComboBox.ComboBox

    '''<summary>
    '''lblPaye control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPaye As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rbPaye control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbPaye As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblParMontant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblParMontant As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbMontant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbMontant As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btRechercheFacture control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btRechercheFacture As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ibExporter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibExporter As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lMessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gvFacture control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvFacture As Global.System.Web.UI.WebControls.GridView
End Class
