'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AffaireFacture

    '''<summary>
    '''ScriptManagerTEST control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManagerTEST As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''mMenuAffaireModif control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mMenuAffaireModif As Global.System.Web.UI.WebControls.Menu

    '''<summary>
    '''tvFacture control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tvFacture As Global.Obout.Ajax.UI.TreeView.Tree

    '''<summary>
    '''lblMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsg As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pIdentification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pIdentification As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblOldRef control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOldRef As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbReferenceFacture control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbReferenceFacture As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblOldLibelle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOldLibelle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbLibelleFacture control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbLibelleFacture As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblOldDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOldDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbDateFacture control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbDateFacture As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblOldHT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOldHT As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbTotHtFacture control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbTotHtFacture As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblOldTTC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOldTTC As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbTotTtcFacture control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbTotTtcFacture As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnModification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnModification As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnSuppression control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSuppression As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnProduits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnProduits As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''pNouvelleFacture control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pNouvelleFacture As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblNewRef control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNewRef As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbFactureRef control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbFactureRef As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''revFactureRef control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents revFactureRef As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''lblMaxReference control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMaxReference As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNewLibelle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNewLibelle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbLibelle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbLibelle As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblNewDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNewDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbFactureDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbFactureDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cCalendrier control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cCalendrier As Global.OboutInc.Calendar2.Calendar

    '''<summary>
    '''cvDateFin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvDateFin As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''lblerror control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblerror As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnAjouter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAjouter As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblerror2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblerror2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rbAffaireProduitType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbAffaireProduitType As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''btnChoix control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnChoix As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblerror3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblerror3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gvFactureSelectProduit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvFactureSelectProduit As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''gvProduitPourcentage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvProduitPourcentage As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''btnConfirmPourcentage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnConfirmPourcentage As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''gvManuelProduit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvManuelProduit As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''btnRetourFiche control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRetourFiche As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnRetourListe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRetourListe As Global.System.Web.UI.WebControls.Button
End Class
